# all languages
languages:
  "简体中文": "zh-CN"
  "English": "en"
  "Französisch": "fr"

# set default language
defaultlang: "English"

# cookie key
cookiekey: "i18n_language"

# set "true" will generate not exist view file when server start
auto_generate_files: true